### ISSUE TITLE
Přidání ID produktu

### ISSUE THREAD

**Issue by zdenekhejl** [pavelsabatka/gtm-heureka#1]
Čau Pavle,

bylo by možné do šablony přidat i odesílání ID produktu? Je to i v oficiální dokumentaci od Heuréky.

![image](https://github.com/pavelsabatka/gtm-heureka/assets/11144885/2f48d0f0-93d9-4ef2-a9c8-0254a194333a)

Díky.

zh

**Comment by pavelsabatka** [comment]
Ahoj Zdeňku,
děkuju za upozornění, tohle mi uteklo.
Opraveno
